#!/usr/bin/env node
/**
 * render_email.mjs — render templates/sponsor-pitch.tsx to HTML and plain text.
 *
 *   node scripts/render_email.mjs [--dossier artifacts/dossier.json]
 *
 * Props come from the dossier and the festival packet. A prop with no evidence behind it
 * is omitted, and the template's own guard drops that section rather than rendering a gap.
 * Both outputs are written: some clients show the text part, and an autogenerated one
 * reads as broken.
 *
 * Two gates run before anything renders, and both refuse rather than warn.
 *
 * The compliance gate: a target the exclusion file blocked never reaches a draft. Bob's
 * own email flagged age and compliance limits on the cannabis names, and a drafted pitch
 * is one copy-paste away from a sent one.
 *
 * The evidence gate: the pitch opens on a dated activation. Without one there is nothing
 * true to say about why this company, now — and the alternative the model reaches for is
 * flattery, which is how a cold pitch identifies itself as automated in its first line.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const arg = (name, dflt) => {
  const i = process.argv.indexOf(`--${name}`);
  return i === -1 ? dflt : process.argv[i + 1];
};
const read = async (p) => JSON.parse(await readFile(resolve(p), "utf8"));

const dossier = await read(arg("dossier", "artifacts/dossier.json"));
const festival = await read(arg("festival", "fixtures/festival-packet.json"));
const f = (name) => dossier.required_fields?.[name]?.value ?? null;

// ---- gate 1: compliance ----------------------------------------------------
if (dossier.gates?.draft_gate === "blocked_compliance") {
  console.error(`Refusing to draft: ${dossier.company} is blocked on compliance.`);
  console.error(`  ${dossier.gates.draft_gate_reason}`);
  console.error(`  Clear it by having the client state the category rule, then re-run.`);
  process.exit(4);
}

// ---- gate 2: a dated reason ------------------------------------------------
const reason = dossier.outreach?.reason_to_engage ?? null;
const reasonUrl = dossier.outreach?.reason_source_url ?? null;
if (reason && !reasonUrl) {
  console.error("Refusing to draft: reason_to_engage has no reason_source_url.");
  console.error("  A claim about the recipient's own activity carries the page it came from.");
  process.exit(4);
}
if (dossier.required_fields?.activation_history?.state !== "retrieved") {
  console.error("Refusing to draft: activation_history is not retrieved.");
  console.error(`  ${dossier.required_fields?.activation_history?.reason ?? "No dated activation signal."}`);
  console.error("  Read an activation page first: npm run signal -- --url <page>");
  process.exit(4);
}

// ---- props -----------------------------------------------------------------
const firstName = String(f("decision_maker") ?? "").split(" ")[0] || null;

const props = {
  recipientFirstName: firstName,
  companyName: dossier.company ?? null,
  festivalName: festival.event_name ?? null,
  festivalDates: `${festival.dates?.start} to ${festival.dates?.end}`,
  festivalVenue: festival.venue?.name ?? null,
  festivalMarket: festival.venue?.market ?? null,
  reason,
  reasonSourceUrl: reasonUrl ?? undefined,
  audienceLine: festival.audience
    ? `Primary audience ${festival.audience.primary_age}, ${festival.audience.region}, household income ${festival.audience.household_income}.`
    : null,
  // Omitted until the client supplies inventory. The template drops the section.
  packageLine: festival.packages?.inventory_state === "unsupplied"
    ? undefined
    : dossier.outreach?.package_named ?? undefined,
  callUrl: festival.sender?.calendly ?? null,
  senderName: festival.sender?.name ?? null,
  senderCompany: festival.sender?.company ?? null,
  optOutUrl: dossier.outreach?.opt_out_url ?? "",
  previewText: dossier.outreach?.preview_text ?? null,
};

const missing = ["recipientFirstName", "companyName", "festivalName", "reason", "callUrl", "previewText"]
  .filter((k) => !props[k]);
if (missing.length) {
  console.error(`Cannot render: ${missing.join(", ")} not populated.`);
  if (missing.includes("recipientFirstName")) {
    console.error("  decision_maker is unknown. Supply an exact LinkedIn profile URL and re-run the calls.");
  }
  process.exit(2);
}

let render;
try {
  ({ render } = await import("@react-email/render"));
} catch {
  console.error("@react-email/render is not installed. Run: npm i -D @react-email/render react react-dom");
  process.exit(3);
}
const { default: SponsorPitch } = await import("../templates/sponsor-pitch.js").catch(() => ({}));
if (!SponsorPitch) {
  console.error("Compile templates/sponsor-pitch.tsx first (tsx/esbuild), then re-run.");
  process.exit(3);
}

await mkdir(resolve("artifacts"), { recursive: true });
const el = SponsorPitch(props);
const html = await render(el);
const text = await render(el, { plainText: true });
await writeFile(resolve("artifacts/pitch.html"), html);
await writeFile(resolve("artifacts/pitch.txt"), text);
await writeFile(resolve("artifacts/pitch.props.json"),
  JSON.stringify({ props, subject: dossier.outreach?.subject ?? null,
                   review_state: "hold",
                   send_state: "draft_only_not_sent",
                   sender_authority: festival.sender?.authority_state ?? "unconfirmed",
                   attendance_omitted: festival.attendance?.state === "disputed" }, null, 2) + "\n");

console.log(`artifacts/pitch.html  ${html.length} bytes`);
console.log(`artifacts/pitch.txt   ${text.length} bytes`);
console.log(`subject: ${dossier.outreach?.subject ?? "(unset)"}`);
console.log("review_state: hold · send_state: draft_only_not_sent");
if (festival.attendance?.state === "disputed") {
  console.log("attendance: omitted — the two client figures do not reconcile");
}
if (festival.packages?.inventory_state === "unsupplied") {
  console.log("package line: omitted — no sponsorship inventory supplied");
}
