#!/usr/bin/env node
/**
 * render_email.mjs — render templates/sponsor-pitch.tsx to HTML and plain text.
 *
 *   node scripts/render_email.mjs [--dossier artifacts/dossier.json]
 *
 * Props come from the dossier and the festival packet. A prop with no evidence behind it
 * is omitted, and the template's own guard drops that section rather than rendering a gap.
 * Both outputs are written: some clients show the text part, and an autogenerated one
 * reads as broken.
 *
 * Two gates run before anything renders, and both refuse rather than warn.
 *
 * The compliance gate: a target the exclusion file blocked never reaches a draft. Bob's
 * own email flagged age and compliance limits on the cannabis names, and a drafted pitch
 * is one copy-paste away from a sent one.
 *
 * The evidence gate: the pitch opens on a dated activation. Without one there is nothing
 * true to say about why this company, now — and the alternative the model reaches for is
 * flattery, which is how a cold pitch identifies itself as automated in its first line.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const arg = (name, dflt) => {
  const i = process.argv.indexOf(`--${name}`);
  return i === -1 ? dflt : process.argv[i + 1];
};
const read = async (p) => JSON.parse(await readFile(resolve(p), "utf8"));

const dossier = await read(arg("dossier", "artifacts/dossier.json"));
const festival = await read(arg("festival", "fixtures/festival-packet.json"));

/** "2026-09-24","2026-09-26" -> "September 24 to 26, 2026" — a reader's date, not a log's. */
function humanDates(startIso, endIso) {
  if (!startIso) return null;
  const months = ["January","February","March","April","May","June","July","August","September","October","November","December"];
  const [sy, sm, sd] = String(startIso).split("-").map(Number);
  const [ey, em, ed] = String(endIso ?? startIso).split("-").map(Number);
  if (sy === ey && sm === em) return `${months[sm - 1]} ${sd} to ${ed}, ${sy}`;
  return `${months[sm - 1]} ${sd} to ${months[em - 1]} ${ed}, ${ey}`;
}
const f = (name) => dossier.required_fields?.[name]?.value ?? null;

// ---- gate 1: compliance ----------------------------------------------------
if (dossier.gates?.draft_gate === "blocked_compliance") {
  console.error(`Refusing to draft: ${dossier.company} is blocked on compliance.`);
  console.error(`  ${dossier.gates.draft_gate_reason}`);
  console.error(`  Clear it by having the client state the category rule, then re-run.`);
  process.exit(4);
}

// ---- gate 2: a dated reason ------------------------------------------------
const reason = dossier.outreach?.reason_to_engage ?? null;
const reasonUrl = dossier.outreach?.reason_source_url ?? null;
if (reason && !reasonUrl) {
  console.error("Refusing to draft: reason_to_engage has no reason_source_url.");
  console.error("  A claim about the recipient's own activity carries the page it came from.");
  process.exit(4);
}
if (dossier.required_fields?.activation_history?.state !== "retrieved") {
  console.error("Refusing to draft: activation_history is not retrieved.");
  console.error(`  ${dossier.required_fields?.activation_history?.reason ?? "No dated activation signal."}`);
  console.error("  Read an activation page first: npm run signal -- --url <page>");
  process.exit(4);
}

// ---- props -----------------------------------------------------------------
const firstName = String(f("decision_maker") ?? "").split(" ")[0] || null;

// The highlighted tier must be the deck's own. Anything else is dropped, because
// availability was never supplied and the sheet may state the rate card and no more.
const rateCard = festival.packages?.rate_card ?? [];
const named = dossier.outreach?.package_named ?? null;
const highlightTier = named && rateCard.some((t) => named.toLowerCase().includes(t.tier.toLowerCase()))
  ? rateCard.find((t) => named.toLowerCase().includes(t.tier.toLowerCase())).tier
  : null;

const props = {
  recipientFirstName: firstName,
  companyName: dossier.company ?? null,
  // The personal note is authored in step 4, in the sender's register; the dated
  // reason is its floor, not its ceiling.
  personalNote: dossier.outreach?.personal_note ?? reason,
  reasonSourceUrl: reasonUrl ?? undefined,
  festivalName: festival.event_name ?? null,
  festivalDates: humanDates(festival.dates?.start, festival.dates?.end),
  festivalVenue: festival.venue?.name ?? null,
  festivalMarket: festival.venue?.market ?? null,
  distanceNote: festival.venue?.distance_note ?? null,
  stages: festival.format?.stages ?? [],
  audienceLine: festival.audience
    ? `Primary audience ${festival.audience.primary_age}, ${festival.audience.region}, household income ${festival.audience.household_income}.`
    : null,
  offerSheet: rateCard,
  highlightTier,
  callUrl: festival.sender?.calendly ?? null,
  senderName: festival.sender?.name ?? null,
  senderCompany: festival.sender?.company ?? null,
  optOutUrl: dossier.outreach?.opt_out_url ?? "",
  previewText: dossier.outreach?.preview_text ?? null,
};

const missing = ["recipientFirstName", "companyName", "festivalName", "personalNote", "callUrl", "previewText"]
  .filter((k) => !props[k]);
if (missing.length) {
  console.error(`Cannot render: ${missing.join(", ")} not populated.`);
  if (missing.includes("recipientFirstName")) {
    console.error("  decision_maker is unknown. Supply an exact LinkedIn profile URL and re-run the calls.");
  }
  process.exit(2);
}

// Zero-build: the template is pure-ESM createElement, so node renders it directly.
let render, SponsorPitch;
try {
  ({ render } = await import("@react-email/render"));
  ({ default: SponsorPitch } = await import(new URL("../templates/sponsor-pitch.mjs", import.meta.url)));
} catch (err) {
  console.error(`Render dependencies missing (${err.message}). Run: npm install`);
  process.exit(3);
}

await mkdir(resolve("artifacts"), { recursive: true });
const el = SponsorPitch(props);
const html = await render(el);
const text = await render(el, { plainText: true });
await writeFile(resolve("artifacts/pitch.html"), html);
await writeFile(resolve("artifacts/pitch.txt"), text);
await writeFile(resolve("artifacts/pitch.props.json"),
  JSON.stringify({ props, subject: dossier.outreach?.subject ?? null,
                   review_state: "hold",
                   send_state: "draft_only_not_sent",
                   sender_authority: festival.sender?.authority_state ?? "unconfirmed",
                   attendance_omitted: festival.attendance?.state === "disputed" }, null, 2) + "\n");

console.log(`artifacts/pitch.html  ${html.length} bytes`);
console.log(`artifacts/pitch.txt   ${text.length} bytes`);
console.log(`subject: ${dossier.outreach?.subject ?? "(unset)"}`);
console.log("review_state: hold · send_state: draft_only_not_sent");
if (festival.attendance?.state === "disputed") {
  console.log("attendance: omitted — the two client figures do not reconcile");
}
console.log(highlightTier
  ? `offer sheet: full rate card, ${highlightTier} highlighted`
  : "offer sheet: full rate card, no tier highlighted");
